version: '3.8'

services:
  nestjs-docker-testing:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - NODE_ENV=production

    environment:
      - NODE_ENV=production
    command: npm run start:prod
