services:
  nestjs-docker-testing:
    container_name: nestjs-docker-testing-container
    ports:
      - '3000:3000'
    env_file:
      - ./.env

  mongo:
    image: mongo:6.0
    restart: always
    env_file:
      - ./.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH: false
    env_file:
      - ./.env
    depends_on:
      - mongo
