version: '3.8'

services:
  nestjs-docker-testing:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run start:dev
